server {
    listen 80;
    server_name 10.157.16.107; #replace the IP with your domain or IP

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 10.157.16.107; #replace the IP with your domain or IP

    ssl_certificate /etc/ssl/certs/selfsigned.crt; #replace the crt file with your certificate file
    ssl_certificate_key /etc/ssl/private/selfsigned.key; #replace the key file with your certificate key file

    location / {
        proxy_pass http://127.0.0.1:3838;  # Adjust this if your app runs on a different port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}
